apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-k8s-demo
  template:
    metadata:
      labels:
        app: spring-boot-k8s-demo
    spec:
      containers:
        - name: spring-boot-k8s-demo
          image: spring-boot-k8s-demo:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /hello
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /hello
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-k8s-demo
spec:
  type: NodePort
  selector:
    app: spring-boot-k8s-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080