spring:
  datasource:
    url: jdbc:mysql://prod-mysql-server:3306/prod_userdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:prod_user}
    password: ${DB_PASSWORD:prod_password}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

server:
  port: 8080
  compression:
    enabled: true
  tomcat:
    max-threads: 200
    min-spare-threads: 10

logging:
  level:
    com.example.user: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.springframework.security: WARN
  file:
    name: /var/log/spring-boot-k8s-demo-prod.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
