spring:
  datasource:
    url: jdbc:mysql://qa-mysql-server:3306/qa_userdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: qa_user
    password: qa_password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: 8080

logging:
  level:
    com.example.user: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
  file:
    name: /var/log/spring-boot-k8s-demo-qa.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
